version: '2'
services:
  web:
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/var/app
  client:
    build: client
    volumes:
      - .:/app
    ports:
      - "9000:9000"
